# GNU Make workspace makefile autogenerated by Premake

.NOTPARALLEL:

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Box2D_config = debug
  GLFW_config = debug
  GLAD_config = debug
  ImGui_config = debug
  freetype_config = debug
  msdfgen_config = debug
  msdf_atlas_gen_config = debug
  yaml_cpp_config = debug
  Kaidel_config = debug
  KaidelCore_config = debug
  KaidelEditor_config = debug
endif
ifeq ($(config),release)
  Box2D_config = release
  GLFW_config = release
  GLAD_config = release
  ImGui_config = release
  freetype_config = release
  msdfgen_config = release
  msdf_atlas_gen_config = release
  yaml_cpp_config = release
  Kaidel_config = release
  KaidelCore_config = release
  KaidelEditor_config = release
endif
ifeq ($(config),dist)
  Box2D_config = dist
  GLFW_config = dist
  GLAD_config = dist
  ImGui_config = dist
  freetype_config = dist
  msdfgen_config = dist
  msdf_atlas_gen_config = dist
  yaml_cpp_config = dist
  Kaidel_config = dist
  KaidelCore_config = dist
  KaidelEditor_config = dist
endif

PROJECTS := Box2D GLFW GLAD ImGui freetype msdfgen msdf-atlas-gen yaml-cpp Kaidel KaidelCore KaidelEditor

.PHONY: all clean help $(PROJECTS) Core Dependencies Tools

all: $(PROJECTS)

Core: Kaidel KaidelCore

Dependencies: Box2D GLAD GLFW ImGui freetype msdf-atlas-gen msdfgen yaml-cpp

Tools: KaidelEditor

Box2D:
ifneq (,$(Box2D_config))
	@echo "==== Building Box2D ($(Box2D_config)) ===="
	@${MAKE} --no-print-directory -C Kaidel/vendor/Box2D -f Makefile config=$(Box2D_config)
endif

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Kaidel/vendor/GLFW -f Makefile config=$(GLFW_config)
endif

GLAD:
ifneq (,$(GLAD_config))
	@echo "==== Building GLAD ($(GLAD_config)) ===="
	@${MAKE} --no-print-directory -C Kaidel/vendor/Glad -f Makefile config=$(GLAD_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "==== Building ImGui ($(ImGui_config)) ===="
	@${MAKE} --no-print-directory -C Kaidel/vendor/imgui -f Makefile config=$(ImGui_config)
endif

freetype:
ifneq (,$(freetype_config))
	@echo "==== Building freetype ($(freetype_config)) ===="
	@${MAKE} --no-print-directory -C Kaidel/vendor/msdf-atlas-gen/msdfgen/freetype -f Makefile config=$(freetype_config)
endif

msdfgen: freetype
ifneq (,$(msdfgen_config))
	@echo "==== Building msdfgen ($(msdfgen_config)) ===="
	@${MAKE} --no-print-directory -C Kaidel/vendor/msdf-atlas-gen/msdfgen -f Makefile config=$(msdfgen_config)
endif

msdf-atlas-gen: msdfgen
ifneq (,$(msdf_atlas_gen_config))
	@echo "==== Building msdf-atlas-gen ($(msdf_atlas_gen_config)) ===="
	@${MAKE} --no-print-directory -C Kaidel/vendor/msdf-atlas-gen -f Makefile config=$(msdf_atlas_gen_config)
endif

yaml-cpp:
ifneq (,$(yaml_cpp_config))
	@echo "==== Building yaml-cpp ($(yaml_cpp_config)) ===="
	@${MAKE} --no-print-directory -C Kaidel/vendor/yaml-cpp -f Makefile config=$(yaml_cpp_config)
endif

Kaidel: Box2D GLFW GLAD ImGui msdf-atlas-gen yaml-cpp
ifneq (,$(Kaidel_config))
	@echo "==== Building Kaidel ($(Kaidel_config)) ===="
	@${MAKE} --no-print-directory -C Kaidel -f Makefile config=$(Kaidel_config)
endif

KaidelCore:
ifneq (,$(KaidelCore_config))
	@echo "==== Building KaidelCore ($(KaidelCore_config)) ===="
	@${MAKE} --no-print-directory -C KaidelCore -f Makefile config=$(KaidelCore_config)
endif

KaidelEditor: Kaidel
ifneq (,$(KaidelEditor_config))
	@echo "==== Building KaidelEditor ($(KaidelEditor_config)) ===="
	@${MAKE} --no-print-directory -C KaidelEditor -f Makefile config=$(KaidelEditor_config)
endif

clean:
	@${MAKE} --no-print-directory -C Kaidel/vendor/Box2D -f Makefile clean
	@${MAKE} --no-print-directory -C Kaidel/vendor/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C Kaidel/vendor/Glad -f Makefile clean
	@${MAKE} --no-print-directory -C Kaidel/vendor/imgui -f Makefile clean
	@${MAKE} --no-print-directory -C Kaidel/vendor/msdf-atlas-gen/msdfgen/freetype -f Makefile clean
	@${MAKE} --no-print-directory -C Kaidel/vendor/msdf-atlas-gen/msdfgen -f Makefile clean
	@${MAKE} --no-print-directory -C Kaidel/vendor/msdf-atlas-gen -f Makefile clean
	@${MAKE} --no-print-directory -C Kaidel/vendor/yaml-cpp -f Makefile clean
	@${MAKE} --no-print-directory -C Kaidel -f Makefile clean
	@${MAKE} --no-print-directory -C KaidelCore -f Makefile clean
	@${MAKE} --no-print-directory -C KaidelEditor -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Box2D"
	@echo "   GLFW"
	@echo "   GLAD"
	@echo "   ImGui"
	@echo "   freetype"
	@echo "   msdfgen"
	@echo "   msdf-atlas-gen"
	@echo "   yaml-cpp"
	@echo "   Kaidel"
	@echo "   KaidelCore"
	@echo "   KaidelEditor"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"